{
  pkgs,
  config,
  isWSL ? false,
  ...
}: let inherit(pkgs) stdenv; gl = config.nixGL.wrapper; in {
  programs.zellij = {
    enable = true;
  };
  programs.ghostty = {
    enable = !stdenv.isDarwin && !isWSL;
    package = gl pkgs.ghostty;
    enableZshIntegration = true;
    installVimSyntax = true;
    settings = {
      font-family = "IosevkaTerm Nerd Font";
      font-size = 11;
      theme = "material-darker";
    };
    themes = {
      material-darker = {
# Scheme: Material Darker
# Generated by Ghostty Base16 Converter
background = "212121";
foreground = "EEFFFF";
selection-background = "353535";
selection-foreground = "212121";
palette = [
"0=#212121"
"1=#F07178"
"2=#C3E88D"
"3=#FFCB6B"
"4=#82AAFF"
"5=#C792EA"
"6=#89DDFF"
"7=#EEFFFF"
"8=#4A4A4A"
"9=#F07178"
"10=#C3E88D"
"11=#FFCB6B"
"12=#82AAFF"
"13=#C792EA"
"14=#89DDFF"
"15=#FFFFFF"
"16=#F78C6C"
"17=#FF5370"
"18=#303030"
"19=#353535"
"20=#B2CCD6"
"21=#EEFFFF"];
      };
    };
  };
  programs.kitty = {
    enable = !isWSL && stdenv.isDarwin;
    package = gl pkgs.kitty;
    font = {
      package = pkgs.nerd-fonts;
      name = "Iosevka";
      size =
        if pkgs.stdenv.isDarwin
        then 13
        else 10;
    };
    settings = {
      adjust_line_height = "130%";
      disable_ligatures = "cursor";
      enable_audio_bell = false;
      visual_bell_duration = "0.1";
      window_margin_width = 0;
      tab_bar_style = "powerline";
      shell = "${pkgs.zellij}/bin/zellij";
    };
    shellIntegration = {
      mode = "enabled";
      enableZshIntegration = true;
    };
    themeFile = "VSCode_Dark";
  };
}
