{
  pkgs,
  config,
  isWSL ? false,
  ...
}: let inherit(pkgs) lib stdenv; gl = config.nixGL.wrapper; ghostty-homebrew-wrapper = pkgs.writeShellApplication {
  name = "ghostty-homebrew-wrapper";
  text = ''
    #!/usr/bin/env bash
    /opt/homebrew/bin/ghostty "$@"
  '';
}; in {
  programs.zellij = {
    enable = true;
  };
  programs.ghostty = {
    enable = !isWSL;
    package = if stdenv.isDarwin then ghostty-homebrew-wrapper else gl pkgs.ghostty;
    enableZshIntegration = true;
    installVimSyntax = true;
    settings = {
      command = "${pkgs.zellij}/bin/zellij";
      font-family = "IosevkaTerm Nerd Font";
      font-size = if stdenv.isDarwin then 14 else 11;
      theme = "material-darker";
      macos-titlebar-style = "transparent";
    };
    themes = {
      material-darker = {
        # Scheme: Material Darker
        # Generated by Ghostty Base16 Converter
        background = "212121";
        foreground = "EEFFFF";
        selection-background = "353535";
        selection-foreground = "212121";
        palette = [
        "0=#212121"
        "1=#F07178"
        "2=#C3E88D"
        "3=#FFCB6B"
        "4=#82AAFF"
        "5=#C792EA"
        "6=#89DDFF"
        "7=#EEFFFF"
        "8=#4A4A4A"
        "9=#F07178"
        "10=#C3E88D"
        "11=#FFCB6B"
        "12=#82AAFF"
        "13=#C792EA"
        "14=#89DDFF"
        "15=#FFFFFF"
        "16=#F78C6C"
        "17=#FF5370"
        "18=#303030"
        "19=#353535"
        "20=#B2CCD6"
        "21=#EEFFFF"];
      };
      syntaxes = lib.mkForce {};
    };
  };
  programs.kitty = {
    enable = false;
    package = gl pkgs.kitty;
    font = {
      package = pkgs.nerd-fonts;
      name = "Iosevka";
      size =
        if pkgs.stdenv.isDarwin
        then 13
        else 10;
    };
    settings = {
      adjust_line_height = "130%";
      disable_ligatures = "cursor";
      enable_audio_bell = false;
      visual_bell_duration = "0.1";
      window_margin_width = 0;
      tab_bar_style = "powerline";
      shell = "${pkgs.zellij}/bin/zellij";
    };
    shellIntegration = {
      mode = "enabled";
      enableZshIntegration = true;
    };
    themeFile = "VSCode_Dark";
  };
}
