{
  pkgs,
  config,
  ...
}: let inherit(pkgs) lib stdenv; gl = config.nixGL.wrapper; ghostty-homebrew-wrapper = pkgs.writeShellApplication {
  name = "ghostty-homebrew-wrapper";
  text = ''
    #!/usr/bin/env bash
    /opt/homebrew/bin/ghostty "$@"
  '';
};
  isWSL = stdenv.isLinux && !config.home.isGraphical; in {
  programs.zellij = {
    enable = true;
    settings.theme = "ansi";
  };
  programs.ghostty = {
    enable = !isWSL;
    package = if stdenv.isDarwin then ghostty-homebrew-wrapper else gl pkgs.ghostty;
    enableZshIntegration = true;
    installVimSyntax = true;
    settings = {
      font-family = "IosevkaTerm Nerd Font";
      font-style = "Medium";
      font-style-bold = "Heavy";
      font-style-italic = "Medium Italic";
      font-style-bold-italic = "Heavy Italic";
      font-size = if stdenv.isDarwin then 14 else 11;
      theme = "catppuccin-mocha";
      macos-titlebar-style = "tabs";
      window-padding-x = 12;
      window-padding-y = 8;
    };
    themes = {
      catppuccin-mocha = {
        palette = [
          "0=#45475a"
          "1=#f38ba8"
          "2=#a6e3a1"
          "3=#f9e2af"
          "4=#89b4fa"
          "5=#f5c2e7"
          "6=#94e2d5"
          "7=#bac2de"
          "8=#585b70"
          "9=#f38ba8"
          "10=#a6e3a1"
          "11=#f9e2af"
          "12=#89b4fa"
          "13=#f5c2e7"
          "14=#94e2d5"
          "15=#a6adc8"
        ];
        background = "1e1e2e";
        foreground = "cdd6f4";
        cursor-color = "f5e0dc";
        cursor-text = "1e1e2e";
        selection-background = "353749";
        selection-foreground = "cdd6f4";
      };
      material-darker = {
        # Scheme: Material Darker
        # Generated by Ghostty Base16 Converter
        background = "212121";
        foreground = "EEFFFF";
        selection-background = "353535";
        selection-foreground = "212121";
        palette = [
          "0=#212121"
          "1=#F07178"
          "2=#C3E88D"
          "3=#FFCB6B"
          "4=#82AAFF"
          "5=#C792EA"
          "6=#89DDFF"
          "7=#EEFFFF"
          "8=#4A4A4A"
          "9=#F07178"
          "10=#C3E88D"
          "11=#FFCB6B"
          "12=#82AAFF"
          "13=#C792EA"
          "14=#89DDFF"
          "15=#FFFFFF"
          "16=#F78C6C"
          "17=#FF5370"
          "18=#303030"
          "19=#353535"
          "20=#B2CCD6"
          "21=#EEFFFF"
        ];
      };
      syntaxes = lib.mkForce {};
    };
  };
  programs.kitty = {
    enable = false;
    package = gl pkgs.kitty;
    font = {
      package = pkgs.nerd-fonts;
      name = "Iosevka";
      size =
        if pkgs.stdenv.isDarwin
        then 13
        else 10;
    };
    settings = {
      adjust_line_height = "130%";
      disable_ligatures = "cursor";
      enable_audio_bell = false;
      visual_bell_duration = "0.1";
      window_margin_width = 0;
      tab_bar_style = "powerline";
    };
    shellIntegration = {
      mode = "enabled";
      enableZshIntegration = true;
    };
    themeFile = "VSCode_Dark";
  };
}
